module.exports = {
    name: 'Marshbout NPCs',
    source: 'zorq',
    type: 'build',
    intro: [
        'The following table can be used as inspiration when an NPC is needed.',
    ],
    // outro: [
    //     'Ideally, this table should be consulted in advance of a situation which would require it, as the results can feed into greater plot hooks.',
    // ],
    caption: 'Marshbout NPCs',
    colLabels: ['Name', 'Description'],
    colStyles: ['col-1 text-center', 'col-3', 'col-8'],
    rows: [
        ["Nancy O'Pug", 'n/a'],
        ['Dame {@creature Clippington Titchwillow|zorq}', 'Landed lady.'],
        [
            '{@creature Branda Earthlord|zorq}',
            'One of the sisters guarding {@creature Soul Rock|zorq}',
        ],
        ['Igno Red McGerf', 'A stupid or oblivious dragon.'],
        ['Cackleburt', 'n/a'],
        ['Bog Frillan', 'n/a'],
        ['{@creature Turkey Badger|zorq}', 'n/a'],
        [
            '{@creature Toestealer|zorq}',
            'A rum gremlin or goblin. Probably hangs out at Throttlebottom Hostlery or The Riskless Tavern',
        ],
        ['Munlin Serplepan', 'n/a'],
        ['Meech', 'n/a'],
        [
            'Flinty Hirsutulous',
            'A slightly hairy, obdurate, unmerciful person.',
        ],
        ['Sir Voke Fit', 'surfeit : voke as in vocare, to call or voice'],
        ['Flange Exgrigio', 'n/a'],

        ['Moker Cornrack', 'n/a'],
        ['Gorty Taygore', 'n/a'],
        ['{@creature Dort Threed|zorq}', 'Commoner'],
        ['{@creature Doodril Manacart|zorq}', 'Commoner'],
        ['Sorashana', 'Commoner'],
        ['Vishara', 'Commoner'],
        ['Yvonna', 'Commoner'],
        ['Tana', 'Commoner'],
        [
            'Ulgor',
            '"UHL gor, some kind of lightning-associated thing (dragonish?)',
        ],
        [
            'Karnish',
            'The spirit of Castle Karn (and the original spirit of the grey tongue). perhaps she too has some association with the fountain.',
        ],
        ['Umpo and Onglo', 'Maybe more of the earthlords ?'],
        ['Tontine', ' "TAHN-teen: some last-alive-gets-all schemer'],
        ['Empo', ''],
        ['Resko', ''],
        ['Raggadochy', 'rag uh DOH chee'],
        ['Pell and Mell', 'wild'],
        ['Nub', '?'],
    ],
};
