module.exports = {
    name: 'Marshbout NPCs',
    source: 'zorq',
    type: 'build',
    intro: [
        'The following table can be used as inspiration when an NPC is needed.',
    ],
    // outro: [
    //     'Ideally, this table should be consulted in advance of a situation which would require it, as the results can feed into greater plot hooks.',
    // ],
    caption: 'Marshbout NPCs',
    colLabels: ['Name', 'Description'],
    colStyles: ['col-1 text-center', 'col-3', 'col-8'],
    rows: [
        [
            "Nancy O'Pug",
            'Human that Miri was shacking up with at Throttlebottom when the Two Horn Band kidnapped Sokka and Zedaar.',
        ],
        ['Dame {@creature Clippington Titchwillow|zorq}', 'Landed lady.'],
        [
            '{@creature Branda Earthlord|zorq}',
            'One of the sisters guarding {@creature Soul Rock|zorq}',
        ],
        ['Igno Red McGerf', 'A stupid or oblivious dragon.'],

        ['Bog Frillan', 'n/a'],
        ['{@creature Turkey Badger|zorq}', 'n/a'],
        [
            '{@creature Toestealer|zorq}',
            {
                type: 'entries',
                entries: [
                    'Miri think she hears someone talking about Toestealer and Owls.',
                    'A rum gremlin or goblin. Probably hangs out at Throttlebottom Hostlery or The Riskless Tavern.',
                ],
            },
        ],
        ['Munlin Serplepan', 'n/a'],
        ['Meech', 'n/a'],
        [
            'Flinty Hirsutulous',
            'A slightly hairy, obdurate, unmerciful person.',
        ],
        ['Sir Voke Fit', 'surfeit : voke as in vocare, to call or voice'],
        ['Flange Exgrigio', 'n/a'],

        ['Moker Cornrack', 'n/a'],
        ['Gorty Taygore', 'n/a'],
        ['{@creature Dort Threed|zorq}', 'Commoner'],
        ['{@creature Doodril Manacart|zorq}', 'Commoner'],
        ['Sorashana', 'Commoner'],
        ['Vishara', 'Commoner'],
        ['Yvonna', 'Commoner'],
        ['Tana', 'Commoner'],
        [
            'Ulgor',
            '"UHL gor, some kind of lightning-associated thing (dragonish?)',
        ],
        [
            'Karnish',
            'The spirit of Castle Karn (and the original spirit of the grey tongue). perhaps she too has some association with the fountain.',
        ],
        ['Umpo and Onglo', 'Maybe more of the earthlords ?'],
        ['Tontine', ' "TAHN-teen: some last-alive-gets-all schemer'],
        ['Empo', ''],
        ['Resko', ''],
        ['Raggadochy', 'rag uh DOH chee'],
        [
            'Pell, Mell, Nell',
            'Three of the kobolds in the {@faction Two Horns|zorq} faction headquartered in the Marshbout marine district.',
        ],
        ['Nub', '?'],
        ['Cotinaminous', 'co-tinaminous (arm, arm)'],
        ['Jumps', 'A jumpy little {@creature dogmole|zorq}'],
        ['Mr. Stabworthy', ''],
        ['A. C. Tockletone', ''],
        ['Aargab', 'gnoll'],
        ['Aaspar', 'female ?? names'],
        ['Agnes', 'hag first name'],
        ['Aguus', 'female ?? names'],
        ['Alark', 'gnoll'],
        ['Almar', ''],
        ['Andak', 'gnoll'],
        ['Arix', 'lizard'],
        ['Arthur (Art) Tapples', 'regular name'],
        ['Ashana', 'quori'],
        ['Ashtai', 'quori'],
        ['Aurangual', 'mind flayer'],
        ['Beluar', 'druid'],
        ['beoff', ''],
        ['Black', 'hag title'],
        ['Cackling', 'hag title'],
        ['Cephalossk', 'mind flayer'],
        ['CHAGBURT/Cadgebort', ''],
        ['Chatterton', ''],
        ['Cheek chunktar', ''],
        ['Corym', 'druid'],
        ['Daealla', 'druid'],
        ['Dalavash', 'kalashtar'],
        ['Dastina', ''],
        ['Denaal', 'female ?? names'],
        ['Dismal', 'hag title'],
        ['Dolishara', 'kalashtar'],
        ['Doodril Manacart', ''],
        ['Dove', ''],
        ['Dowson', ''],
        ['Draraar', 'female ?? names'],
        ['Dread', 'hag title'],
        ['Driftwood', ''],
        ['Drukt', 'mind flayer'],
        ['Drusiss', 'mind flayer'],
        ['Duusha', 'female ?? names'],
        ['Ekhaas', 'female ?? names'],
        ['Eltaeor', 'druid'],
        ['Eluun', 'female ?? names'],
        ['Escant', 'title'],
        ['Ethak', 'gnoll'],
        ['Ett', 'kobold'],
        ['Euonymus nick: "last trace"', ''],
        ['Extander Vleshmiy', ''],
        ['Eyeth', 'gnoll'],
        ['Fawney Rig', ''],
        ['Fedlan', ''],
        ['Flamuelle', ''],
        ['Gaduul', 'female ?? names'],
        ['garfod  the magcharfalent', ''],
        ['georbe', ''],
        ['Gerator', 'title'],
        ['giblinoid', ''],
        ['Girdle', ''],
        ['Gnokles', ''],
        ['Gnokles (NOH-cuhls)', ''],
        ['Goosewood', ''],
        ['Granny', 'hag title'],
        ['Grash', 'orc?'],
        ['Greenteeth', 'hag last name'],
        ['Ha', 'kalashtar'],
        ['Hareth', 'quori'],
        ['Harlequino', ''],
        ['harney', ''],
        ['Hashak', 'female ?? names'],
        ['Hebwith', ''],
        ['Hieronymo', ''],
        ['Hostrena Butterknife', ''],
        [
            'https://en.wiktionary.org/wiki/Category:Old_High_German_given_names',
            '',
        ],
        ['Hygglla ongott', ''],
        ['Ignar', 'gnoll'],
        ['Innar', ''],
        ['Irtos', 'kobold'],
        ['Isfand', ''],
        ['Ishara', 'quori'],
        ['Janza / Ganza / Gazaca ("Our treasure")', 'Gnoll towns'],
        ['Jesse Luckett', ''],
        ['Jheluum', 'female ?? names'],
        ['Kashak', 'kobold'],
        ['Kashak', 'lizard'],
        ['Kelaal', 'female ?? names'],
        ['Khad', 'quori'],
        ['Khoratari', ''],
        ['Knottypate', ''],
        ['Knucklebones', 'hag last name'],
        ['Kosh', 'quori'],
        ['lakosh', ''],
        ['Lanhareth', ''],
        ['leer', 'unit of measure'],
        ['Leylan', ''],
        ['Locustay', ''],
        ['Lugribossk', 'mind flayer'],
        ['Lummur', ''],
        ['Lunchasaurus', ''],
        ['Madge Parsons', ''],
        ['MAGGIE FLOOD', ''],
        [
            'Male Names: Aruget, Chetiin, Daavn, Dabrak, Dagii, Drevduul, Duulan, Fenic, Gudruun, Haluun, Haruuc, Jhazaal, Kallaad, Krakuul, Krootad, Mazaan',
            '',
        ],
        ['MARY COBBLESTONE', ''],
        ['Mathilda', 'hag first name'],
        ['May', 'hag first name'],
        ['Meepo', 'kobold'],
        ['Melk', 'quori'],
        ['Mensil(r/n)oy', ''],
        ['Middenheap', 'hag last name'],
        ['Molavakri ', ''],
        ['Molo', 'kobold'],
        ['Morgan', 'hag first name'],
        ['Mudwallow', 'hag last name'],
        ['Nari', 'quori'],
        ['Nash', ''],
        ['Nasree', 'female ?? names'],
        ['Natalie', ''],
        ['Nevitash ', ''],
        ['Nisi Siurp (SEE-urp)', ''],
        ['Nunce', ''],
        ['Odell', ''],
        ['Oduk', 'gnoll'],
        ['Ohsoss', 'kobold'],
        ['Old', 'hag title'],
        ['Olga', 'hag first name'],
        ['Onfalon', 'title'],
        ['ORP FREEN', ''],

        ['Otal', 'gnoll'],
        ['Panzon', ''],
        ['PHERMASTAPHY', 'title; location'],
        ['Phineas Fletcher', ''],
        ['phoenix underscramble', ''],
        ['Pigtooth', 'hag last name'],
        ['Polly', 'hag first name'],
        ['Pollyon (pahl-ee-ohn', ''],
        ['Queue Orius', ''],
        ['Quoor', 'mind flayer'],
        ['Ragdar', ''],
        ['Rakari', ''],
        ['Ralayan', 'mind flayer'],
        ['Raleen', 'female ?? names'],
        ['Raznah', ''],
        ['Razu', 'female ?? names'],
        ['Rekseen', 'female ?? names'],
        ['Reksiit', ''],
        ['Rickety', 'hag title'],
        ['ROJEK', ''],
        ['Rolphe Nustle', ''],
        ['Rotom', 'kobold'],
        ['S’venchen', 'mind flayer'],
        ['Sagin', 'kobold'],
        ['Sally', 'hag first name'],
        ['Sardsult', 'mind flayer'],
        ['Scudge Horpoth', ''],
        ['Senen', 'female ?? names'],
        ['Shahar', ''],
        ['Shedroor', 'female ?? names'],
        ['Sik', 'kobold'],
        ['Slab Denchmeat', ''],
        ['Sleggy', ''],
        ['Sniv', 'kobold'],
        ['Spiner', 'street'],
        ['Tajiin', 'female ?? names'],
        ['Taklak', 'lizard, kobold'],
        ['Tana', 'quori'],
        ['tana', ''],
        ['Tari', 'quori'],
        ['Tariic', ''],
        ['Taruuzh', ''],
        ['Tash', 'quori'],
        ['Tes', 'kobold'],
        ['Tharcereli', 'mind flayer'],
        ['the Imponderable', 'epithet'],
        ['The raggle', 'title, name'],
        ['Thuun ("Thun")', ''],
        ['Tooshie', ''],
        ['Toprick', 'dwarf surname'],
        ['Torashtai', ''],
        ['Trabis', ''],
        ['TumTum', ''],
        ['Tuneer', 'female ?? names'],
        ['Turtleback', 'hag title'],
        ['Twigmouth', 'hag last name'],
        ['Uddubera Orepin', ''],
        ['Ulad', 'quori'],
        ['Ulthak', 'gnoll'],
        ['Ursula', 'hag first name'],
        ['Ustar', 'gnoll'],
        ['Vakri', 'quori'],
        ['Valakhad ', ''],
        ['Valii', 'female ?? names'],
        ['Vanii', ''],
        ['Vanon ', ''],
        ['Varn', 'kobold'],

        ['VENDALI(UM/OM) ', 'title'],
        ['Virgat(e)', 'title'],
        ['Wehmseiper', 'group?'],
        ['Wicked', 'hag title'],
        ['Wormwiggle', 'hag last name'],
        ['Wuudaraj', ''],
        ['Zellix', 'mind flayer'],
        ['Gind', '??'],
        ['Boolook', 'Very good at falling asleep quickly'],
    ],
};
